version: '3.3'

services:
  airs-router:
    image: ${DOCKER_LOGIN}/directcd:1.1
    command:
      - pull
      - --repo=https://github.com/untillpro/airs-router
      - -o=out.exe
      - -t=10
      - -w=tmp
      - --
      - -ch=traefik_consul_server -ns=n_nats1,n_nats2,n_nats3
    deploy:
      labels:
        - traefik.enable=true
        - traefik.frontend.rule=PathPrefixStrip:/airs-router
        - traefik.port=8822
        - traefik.docker.network=webgateway
    networks:
      - traefik
      - webgateway

networks:
  traefik:
    external: true
  webgateway:
    external: true